In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/thesis_ppd/PPD_data.csv')
print(df.shape)
df.head(10)

(800, 70)

,sr,Age,Residence,Education Level,Marital status,Occupation before latest pregnancy,Monthly income before latest pregnancy,Occupation After Your Latest Childbirth,Current monthly income,Husband's education level,...,You have blamed myself unnecessarily when things went wrong,You have been anxious or worried for no good reason,You have felt scared or panicky for no good reason,Things have been getting to you,You have been so unhappy that you have had difficulty sleeping,You have felt sad or miserable,You have been so unhappy that you have been crying,The thought of harming yourself has occurred,EPDS Score,EPDS Result
0,1,24,City,University,Married,Student,NaN,Student,NaN,University,...,Not at all,Nearly every day,Not at all,Several days,Not at all,Nearly every day,Not at all,Not at all,13,High
1,2,31,City,University,Divorced,Doctor,10000 to 20000,Doctor,10000 to 20000,NaN,...,Around half the days,Nearly every day,Around half the days,Nearly every day,Several days,Nearly every day,Around half the days,Not at all,20,High
2,3,31,City,University,Married,Service,10000 to 20000,Service,10000 to 20000,University,...,Several days,Nearly every day,Several days,Not at all,Nearly every day,Nearly every day,Several days,Not at all,16,High
3,4,32,City,University,Married,Doctor,More than 30000,Doctor,More than 30000,University,...,Not at all,Not at all,Not at all,Not at all,Several days,Not at all,Not at all,Not at all,5,Low
4,5,27,City,University,Married,Housewife,NaN,Housewife,NaN,University,...,Not at all,Not at all,Not at all,Not at all,Nearly every day,Not at all,Not at all,Not at all,7,Low
5,6,24,City,University,Married,Student,NaN,Student,NaN,University,...,Nearly every day,Nearly every day,Nearly every day,Around half the days,Not at all,Nearly every day,Nearly every day,Not at all,23,High
6,7,29,City,University,Married,Service,More than 30000,Service,More than 30000,University,...,Nearly every day,Nearly every day,Nearly every day,Nearly every day,Nearly every day,Nearly every day,Nearly every day,Nearly every day,30,High
7,8,30,Village,University,Married,Doctor,More than 30000,Doctor,More than 30000,University,...,Not at all,Not at all,Not at all,Not at all,Nearly every day,Not at all,Not at all,Not at all,3,Low
8,9,29,City,University,Married,Housewife,NaN,Housewife,NaN,University,...,Around half the days,Around half the days,Not at all,Around half the days,Several days,Around half the days,Around half the days,Not at all,15,High
9,10,23,City,University,Married,Housewife,NaN,Housewife,NaN,University,...,Not at all,Not at all,Not at all,Not at all,Nearly every day,Not at all,Not at all,Not at all,3,Low

In [ ]:
df.drop(columns=['sr'], inplace=True)

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace("’", "'", regex=False)
)

df.rename(columns={
    "Recieved Support": "Received Support",
    "rouble concentrating on things": "Trouble concentrating on things",
    "Birth compliancy": "Birth complications"
}, inplace=True)

df.columns.tolist()

['Age',
 'Residence',
 'Education Level',
 'Marital status',
 'Occupation before latest pregnancy',
 'Monthly income before latest pregnancy',
 'Occupation After Your Latest Childbirth',
 'Current monthly income',
 "Husband's education level",
 "Husband's monthly income",
 'Addiction',
 'Total children',
 'Disease before pregnancy',
 'History of pregnancy loss',
 'Family type',
 'Number of household members',
 'Relationship with the in-laws',
 'Relationship with husband',
 'Relationship with the newborn',
 'Relationship between father and newborn',
 'Feeling about motherhood',
 'Received Support',
 'Need for Support',
 'Major changes or losses during pregnancy',
 'Abuse',
 'Trust and share feelings',
 'Number of the latest pregnancy',
 'Pregnancy length',
 'Pregnancy plan',
 'Regular checkups',
 'Fear of pregnancy',
 'Diseases during pregnancy',
 'Age of newborn',
 'Age of immediate older children',
 'Mode of delivery',
 'Gender of newborn',
 'Birth complications',
 'Breastfeed',
 'Newborn illness',
 'Worry about newborn',
 'Relax/sleep when newborn is tended',
 'Relax/sleep when the newborn is asleep',
 'Angry after latest child birth',
 'Feeling for regular activities',
 'Depression before pregnancy (PHQ2)',
 'Depression during pregnancy (PHQ2)',
 'Little interest or pleasure in doing things',
 'Feeling down, depressed, or hopeless',
 'Trouble falling or staying asleep, or sleeping too much',
 'Feeling tired or having little energy',
 'Poor appetite or overeating',
 'Feeling bad about yourself or that you are a failure or have let yourself or your family down',
 'Trouble concentrating on things',
 'Moving or speaking or restlessness',
 'Thoughts that you would be better off dead, or of hurting yourself',
 'PHQ9 Score',
 'PHQ9 Result',
 'You have been able to laugh and see the funny side of things',
 'You have looked forward with enjoyment to things',
 'You have blamed myself unnecessarily when things went wrong',
 'You have been anxious or worried for no good reason',
 'You have felt scared or panicky for no good reason',
 'Things have been getting to you',
 'You have been so unhappy that you have had difficulty sleeping',
 'You have felt sad or miserable',
 'You have been so unhappy that you have been crying',
 'The thought of harming yourself has occurred',
 'EPDS Score',
 'EPDS Result']

**FRequncies**

In [ ]:
import pandas as pd

# Identify categorical columns (object type)
categorical_cols = df.select_dtypes(include=['object']).columns

# Loop through each categorical column and display frequency/percentage
for col in categorical_cols:
    print(f"--- Frequency and Percentage for: {col} ---")

    counts = df[col].value_counts(dropna=False)
    percentages = df[col].value_counts(dropna=False, normalize=True) * 100

    # Combine into a summary table
    cat_stats = pd.DataFrame({
        'Frequency': counts,
        'Percentage (%)': percentages
    })

    display(cat_stats)
    print("\n")

--- Frequency and Percentage for: Residence ---

           Frequency  Percentage (%)
Residence
City             637          79.625
Village          163          20.375

--- Frequency and Percentage for: Education Level ---

                 Frequency  Percentage (%)
Education Level
University             588          73.500
College                 99          12.375
High School             62           7.750
Primary School          25           3.125
Primary school          11           1.375
High school              9           1.125
NaN                      6           0.750

--- Frequency and Percentage for: Marital status ---

                Frequency  Percentage (%)
Marital status
Married               795          99.375
Divorced                5           0.625

--- Frequency and Percentage for: Occupation before latest pregnancy ---

                                    Frequency  Percentage (%)
Occupation before latest pregnancy
Housewife                                 390          48.750
Student                                   139          17.375
Teacher                                    78           9.750
Service                                    74           9.250
Other                                      65           8.125
Doctor                                     40           5.000
Business                                   13           1.625
House wife                                  1           0.125

--- Frequency and Percentage for: Monthly income before latest pregnancy ---

                                        Frequency  Percentage (%)
Monthly income before latest pregnancy
NaN                                           437          54.625
10000 to 20000                                 92          11.500
5000 to 10000                                  86          10.750
20000 to 30000                                 77           9.625
More than 30000                                71           8.875
Less than 5000                                 37           4.625

--- Frequency and Percentage for: Occupation After Your Latest Childbirth ---

                                         Frequency  Percentage (%)
Occupation After Your Latest Childbirth
Housewife                                      534          66.750
Student                                         70           8.750
Service                                         59           7.375
Teacher                                         47           5.875
Doctor                                          38           4.750
Other                                           37           4.625
Business                                        14           1.750
House wife                                       1           0.125

--- Frequency and Percentage for: Current monthly income ---

                        Frequency  Percentage (%)
Current monthly income
NaN                           525          65.625
10000 to 20000                 66           8.250
More than 30000                64           8.000
20000 to 30000                 63           7.875
5000 to 10000                  42           5.250
Less than 5000                 40           5.000

--- Frequency and Percentage for: Husband's education level ---

                           Frequency  Percentage (%)
Husband's education level
University                       595          74.375
College                           75           9.375
High School                       75           9.375
Primary School                    32           4.000
NaN                                9           1.125
High school                        8           1.000
Primary school                     6           0.750

--- Frequency and Percentage for: Husband's monthly income ---

                          Frequency  Percentage (%)
Husband's monthly income
More than 30000                 343          42.875
20000 to 30000                  207          25.875
10000 to 20000                  146          18.250
5000 to 10000                    65           8.125
NaN                              28           3.500
Less than 5000                   11           1.375

--- Frequency and Percentage for: Addiction ---

           Frequency  Percentage (%)
Addiction
NaN              789          98.625
Smoking            8           1.000
Drinking           2           0.250
Drugs              1           0.125

--- Frequency and Percentage for: Total children ---

                Frequency  Percentage (%)
Total children
One                   518          64.750
Two                   223          27.875
More than two          50           6.250
More than Two           9           1.125

--- Frequency and Percentage for: Disease before pregnancy ---

                          Frequency  Percentage (%)
Disease before pregnancy
NaN                             588          73.500
Chronic Disease                 124          15.500
Non-Chronic Disease              87          10.875
1.2                               1           0.125

--- Frequency and Percentage for: History of pregnancy loss ---

                           Frequency  Percentage (%)
History of pregnancy loss
NaN                              613          76.625
Miscarriage                      158          19.750
Still-born Delivery               24           3.000
Still-born delivery                5           0.625

--- Frequency and Percentage for: Family type ---

             Frequency  Percentage (%)
Family type
Nuclear            421          52.625
Joint              379          47.375

--- Frequency and Percentage for: Number of household members ---

                             Frequency  Percentage (%)
Number of household members
2 to 5                             524          65.500
6 to 8                             223          27.875
9 or more                           53           6.625

--- Frequency and Percentage for: Relationship with the in-laws ---

                               Frequency  Percentage (%)
Relationship with the in-laws
Neutral                              315          39.375
Good                                 310          38.750
Bad                                  134          16.750
Friendly                              33           4.125
Poor                                   8           1.000

--- Frequency and Percentage for: Relationship with husband ---

                           Frequency  Percentage (%)
Relationship with husband
Good                             578          72.250
Neutral                          113          14.125
Friendly                          52           6.500
Bad                               51           6.375
Poor                               6           0.750

--- Frequency and Percentage for: Relationship with the newborn ---

                               Frequency  Percentage (%)
Relationship with the newborn
Good                                 690          86.250
Very good                             65           8.125
Neutral                               38           4.750
Bad                                    7           0.875

--- Frequency and Percentage for: Relationship between father and newborn ---

                                         Frequency  Percentage (%)
Relationship between father and newborn
Good                                           654          81.750
Neutral                                         69           8.625
Very good                                       62           7.750
Bad                                             15           1.875

--- Frequency and Percentage for: Feeling about motherhood ---

                          Frequency  Percentage (%)
Feeling about motherhood
Happy                           671          83.875
Neutral                          94          11.750
Sad                              35           4.375

--- Frequency and Percentage for: Received Support ---

                  Frequency  Percentage (%)
Received Support
Medium                  339          42.375
High                    307          38.375
Low                     154          19.250

--- Frequency and Percentage for: Need for Support ---

                  Frequency  Percentage (%)
Need for Support
Low                     523          65.375
NaN                     167          20.875
Medium                   85          10.625
High                     25           3.125

--- Frequency and Percentage for: Major changes or losses during pregnancy ---

                                          Frequency  Percentage (%)
Major changes or losses during pregnancy
No                                              526           65.75
Yes                                             274           34.25

--- Frequency and Percentage for: Abuse ---

       Frequency  Percentage (%)
Abuse
Yes          403          50.375
No           359          44.875
NaN           38           4.750

--- Frequency and Percentage for: Trust and share feelings ---

                          Frequency  Percentage (%)
Trust and share feelings
Yes                             544          68.000
No                              255          31.875
NaN                               1           0.125

--- Frequency and Percentage for: Pregnancy length ---

                    Frequency  Percentage (%)
Pregnancy length
9 months                  438          54.750
10 months                 246          30.750
8 months                   71           8.875
Less than 5 months         22           2.750
7 months                   16           2.000
6 months                    7           0.875

--- Frequency and Percentage for: Pregnancy plan ---

                Frequency  Percentage (%)
Pregnancy plan
Yes                   568            71.0
No                    232            29.0

--- Frequency and Percentage for: Regular checkups ---

                  Frequency  Percentage (%)
Regular checkups
Yes                     752            94.0
No                       48             6.0

--- Frequency and Percentage for: Fear of pregnancy ---

                   Frequency  Percentage (%)
Fear of pregnancy
Yes                      486           60.75
No                       314           39.25

--- Frequency and Percentage for: Diseases during pregnancy ---

                           Frequency  Percentage (%)
Diseases during pregnancy
NaN                              371          46.375
Non-Chronic Disease              279          34.875
Chronic Disease                  121          15.125
Non-chronic disease               16           2.000
Chronic disease                   13           1.625

--- Frequency and Percentage for: Age of newborn ---

                     Frequency  Percentage (%)
Age of newborn
0 to 6 months              344          43.000
1 year to 1.5 year         155          19.375
6 months to 1 year         153          19.125
Older than 1.5 year        148          18.500

--- Frequency and Percentage for: Age of immediate older children ---

                                 Frequency  Percentage (%)
Age of immediate older children
NaN                                    517          64.625
4yr to 6yr                             112          14.000
1yr to 3yr                             109          13.625
7yr to 12yr                             55           6.875
13yr or more                             7           0.875

--- Frequency and Percentage for: Mode of delivery ---

                   Frequency  Percentage (%)
Mode of delivery
Caesarean Section        560            70.0
Normal Delivery          240            30.0

--- Frequency and Percentage for: Gender of newborn ---

                   Frequency  Percentage (%)
Gender of newborn
Boy                      409          51.125
Girl                     391          48.875

--- Frequency and Percentage for: Birth complications ---

                     Frequency  Percentage (%)
Birth complications
No                         487          60.875
Yes                        313          39.125

--- Frequency and Percentage for: Breastfeed ---

            Frequency  Percentage (%)
Breastfeed
Yes               719          89.875
No                 81          10.125

--- Frequency and Percentage for: Newborn illness ---

                 Frequency  Percentage (%)
Newborn illness
No                     662           82.75
Yes                    138           17.25

--- Frequency and Percentage for: Worry about newborn ---

                     Frequency  Percentage (%)
Worry about newborn
Yes                        470           58.75
No                         330           41.25

--- Frequency and Percentage for: Relax/sleep when newborn is tended ---

                                    Frequency  Percentage (%)
Relax/sleep when newborn is tended
Yes                                       455          56.875
No                                        345          43.125

--- Frequency and Percentage for: Relax/sleep when the newborn is asleep ---

                                        Frequency  Percentage (%)
Relax/sleep when the newborn is asleep
Yes                                           594           74.25
No                                            206           25.75

--- Frequency and Percentage for: Angry after latest child birth ---

                                Frequency  Percentage (%)
Angry after latest child birth
Yes                                   539          67.375
No                                    261          32.625

--- Frequency and Percentage for: Feeling for regular activities ---

                                Frequency  Percentage (%)
Feeling for regular activities
Tired                                 335          41.875
NaN                                   223          27.875
Worried                               175          21.875
Afraid                                 67           8.375

--- Frequency and Percentage for: Depression before pregnancy (PHQ2) ---

                                    Frequency  Percentage (%)
Depression before pregnancy (PHQ2)
Negative                                  719          89.875
Positive                                   81          10.125

--- Frequency and Percentage for: Depression during pregnancy (PHQ2) ---

                                    Frequency  Percentage (%)
Depression during pregnancy (PHQ2)
Negative                                  616            77.0
Positive                                  184            23.0

--- Frequency and Percentage for: Little interest or pleasure in doing things ---

                                             Frequency  Percentage (%)
Little interest or pleasure in doing things
Around half the days                               410           51.25
Not at all                                         254           31.75
Nearly every day                                   136           17.00

--- Frequency and Percentage for: Feeling down, depressed, or hopeless ---

                                      Frequency  Percentage (%)
Feeling down, depressed, or hopeless
Several days                                284          35.500
Nearly every day                            215          26.875
Not at all                                  159          19.875
Several Days                                 72           9.000
Around half the days                         65           8.125
মাঝে মধ্যে (Several days)                     5           0.625

--- Frequency and Percentage for: Trouble falling or staying asleep, or sleeping too much ---

                                                    Frequency  Percentage (%)
Trouble falling or staying asleep, or sleeping ...
Nearly every day                                          325          40.625
Several days                                              229          28.625
Not at all                                                110          13.750
Around half the days                                       69           8.625
Several Days                                               62           7.750
মাঝে মধ্যে (Several days)                                   5           0.625

--- Frequency and Percentage for: Feeling tired or having little energy ---

                                       Frequency  Percentage (%)
Feeling tired or having little energy
Several days                                 333          41.625
Nearly every day                             234          29.250
Several Days                                  83          10.375
Around half the days                          77           9.625
Not at all                                    73           9.125

--- Frequency and Percentage for: Poor appetite or overeating ---

                             Frequency  Percentage (%)
Poor appetite or overeating
Several Days                       338          42.250
Not at all                         218          27.250
Nearly every day                   115          14.375
Around half the days                93          11.625
Several days                        36           4.500

--- Frequency and Percentage for: Feeling bad about yourself or that you are a failure or have let yourself or your family down ---

                                                    Frequency  Percentage (%)
Feeling bad about yourself or that you are a fa...
Not at all                                                299          37.375
Several Days                                              292          36.500
Nearly every day                                          128          16.000
Around half the days                                       49           6.125
Several days                                               32           4.000

--- Frequency and Percentage for: Trouble concentrating on things ---

                                 Frequency  Percentage (%)
Trouble concentrating on things
Several Days                           347          43.375
Nearly every day                       179          22.375
Not at all                             173          21.625
Around half the days                    59           7.375
Several days                            42           5.250

--- Frequency and Percentage for: Moving or speaking or restlessness ---

                                    Frequency  Percentage (%)
Moving or speaking or restlessness
Not at all                                288          36.000
Several Days                              259          32.375
Nearly every day                          161          20.125
Around half the days                       59           7.375
Several days                               33           4.125

--- Frequency and Percentage for: Thoughts that you would be better off dead, or of hurting yourself ---

                                                    Frequency  Percentage (%)
Thoughts that you would be better off dead, or ...
Not at all                                                598          74.750
Several Days                                              145          18.125
Nearly every day                                           29           3.625
Around half the days                                       22           2.750
Several days                                                6           0.750

--- Frequency and Percentage for: PHQ9 Result ---

                   Frequency  Percentage (%)
PHQ9 Result
Moderate                 237          29.625
Mild                     231          28.875
Moderately Severe        132          16.500
Minimal                  103          12.875
Severe                    89          11.125
Normal                     8           1.000

--- Frequency and Percentage for: You have been able to laugh and see the funny side of things ---

                                                    Frequency  Percentage (%)
You have been able to laugh and see the funny s...
Several days                                              328          41.000
Nearly every day                                          169          21.125
Not at all                                                136          17.000
Around half the days                                       85          10.625
Several Days                                               80          10.000
মাঝে মধ্যে (Several days)                                   2           0.250

--- Frequency and Percentage for: You have looked forward with enjoyment to things ---

                                                  Frequency  Percentage (%)
You have looked forward with enjoyment to things
Several days                                            328          41.000
Nearly every day                                        169          21.125
Not at all                                              136          17.000
Around half the days                                     85          10.625
Several Days                                             80          10.000
মাঝে মধ্যে (Several days)                                 2           0.250

--- Frequency and Percentage for: You have blamed myself unnecessarily when things went wrong ---

                                                    Frequency  Percentage (%)
You have blamed myself unnecessarily when thing...
Not at all                                                299          37.375
Several days                                              256          32.000
Nearly every day                                          128          16.000
Several Days                                               67           8.375
Around half the days                                       49           6.125
মাঝে মধ্যে (Several days)                                   1           0.125

--- Frequency and Percentage for: You have been anxious or worried for no good reason ---

                                                    Frequency  Percentage (%)
You have been anxious or worried for no good re...
Several days                                              284          35.500
Nearly every day                                          215          26.875
Not at all                                                159          19.875
Several Days                                               72           9.000
Around half the days                                       65           8.125
মাঝে মধ্যে (Several days)                                   5           0.625

--- Frequency and Percentage for: You have felt scared or panicky for no good reason ---

                                                    Frequency  Percentage (%)
You have felt scared or panicky for no good reason
Not at all                                                369          46.125
Several days                                              235          29.375
Nearly every day                                          107          13.375
Several Days                                               51           6.375
Around half the days                                       37           4.625
মাঝে মধ্যে (Several days)                                   1           0.125

--- Frequency and Percentage for: Things have been getting to you ---

                                 Frequency  Percentage (%)
Things have been getting to you
Several days                           306          38.250
Nearly every day                       179          22.375
Not at all                             173          21.625
Several Days                            81          10.125
Around half the days                    59           7.375
মাঝে মধ্যে (Several days)                2           0.250

--- Frequency and Percentage for: You have been so unhappy that you have had difficulty sleeping ---

                                                    Frequency  Percentage (%)
You have been so unhappy that you have had diff...
Nearly every day                                          325          40.625
Several days                                              229          28.625
Not at all                                                110          13.750
Around half the days                                       69           8.625
Several Days                                               62           7.750
মাঝে মধ্যে (Several days)                                   5           0.625

--- Frequency and Percentage for: You have felt sad or miserable ---

                                Frequency  Percentage (%)
You have felt sad or miserable
Several days                          284          35.500
Nearly every day                      215          26.875
Not at all                            159          19.875
Several Days                           72           9.000
Around half the days                   65           8.125
মাঝে মধ্যে (Several days)               5           0.625

--- Frequency and Percentage for: You have been so unhappy that you have been crying ---

                                                    Frequency  Percentage (%)
You have been so unhappy that you have been crying
Several days                                              342          42.750
Not at all                                                217          27.125
Nearly every day                                          116          14.500
Several Days                                               70           8.750
Around half the days                                       50           6.250
মাঝে মধ্যে (Several days)                                   5           0.625

--- Frequency and Percentage for: The thought of harming yourself has occurred ---

                                              Frequency  Percentage (%)
The thought of harming yourself has occurred
Not at all                                          598          74.750
Several days                                        117          14.625
Several Days                                         34           4.250
Nearly every day                                     29           3.625
Around half the days                                 22           2.750

--- Frequency and Percentage for: EPDS Result ---

             Frequency  Percentage (%)
EPDS Result
High               350           43.75
Low                260           32.50
Medium             190           23.75

In [ ]:
df['Education Level'] = df['Education Level'].replace({
    'High school': 'High School',
    'Primary school': 'Primary School'
})

# Verify the changes
print(df['Education Level'].value_counts())

Education Level
University        588
College            99
High School        71
Primary School     36
Name: count, dtype: int64

In [ ]:
df["Husband's education level"] = df["Husband's education level"].replace({
    'High school': 'High School',
    'Primary school': 'Primary School'
})

# Verify the changes
print(df["Husband's education level"].value_counts())

Husband's education level
University        595
High School        83
College            75
Primary School     38
Name: count, dtype: int64

Total children column fixed

In [ ]:
df['Total children'] = df['Total children'].replace('More than two', 'More than Two')

# Verify the change
print("Updated 'Total children' counts:")
print(df['Total children'].value_counts())

Updated 'Total children' counts:
Total children
One              518
Two              223
More than Two     59
Name: count, dtype: int64

HIstory of pregnancy loss

In [ ]:
df['History of pregnancy loss'] = df['History of pregnancy loss'].replace('Still-born delivery', 'Still-born Delivery')

# Verify the change
print("Updated 'History of pregnancy loss' counts:")
print(df['History of pregnancy loss'].value_counts(dropna=False))

Updated 'History of pregnancy loss' counts:
History of pregnancy loss
NaN                    613
Miscarriage            158
Still-born Delivery     29
Name: count, dtype: int64

In [ ]:
col_target = 'Disease before pregnancy'
counts = df[col_target].value_counts(dropna=False)
percentages = df[col_target].value_counts(dropna=False, normalize=True) * 100

freq_table = pd.DataFrame({
    'Frequency': counts,
    'Percentage (%)': percentages
})

print(f'--- Frequency Distribution for: {col_target} ---')
display(freq_table)

--- Frequency Distribution for: Disease before pregnancy ---

                          Frequency  Percentage (%)
Disease before pregnancy
NaN                             588          73.500
Chronic Disease                 124          15.500
Non-Chronic Disease              87          10.875
1.2                               1           0.125

In [ ]:
import numpy as np

# Target column name (stripping spaces to be safe)
col_target = 'Disease before pregnancy'

# Replace the specific '1.2' value with NaN
df[col_target] = df[col_target].replace('1.2', np.nan)

# Display the new frequencies including NaNs
counts = df[col_target].value_counts(dropna=False)
percentages = df[col_target].value_counts(dropna=False, normalize=True) * 100

freq_table = pd.DataFrame({
    'Frequency': counts,
    'Percentage (%)': percentages
})

print(f'--- Updated Frequencies for: {col_target} ---')
display(freq_table)

--- Updated Frequencies for: Disease before pregnancy ---

                          Frequency  Percentage (%)
Disease before pregnancy
NaN                             589          73.625
Chronic Disease                 124          15.500
Non-Chronic Disease              87          10.875

In [ ]:
#Fix inconsistent category values
# -----------------------------
df = df.replace({

    'Chronic disease': 'Chronic Disease',
    'Non-chronic disease': 'Non-Chronic Disease',
    'Non-chronic Disease': 'Non-Chronic Disease',
})

In [ ]:
col_target = 'Diseases during pregnancy'
counts = df[col_target].value_counts(dropna=False)
percentages = df[col_target].value_counts(dropna=False, normalize=True) * 100

freq_table = pd.DataFrame({
    'Frequency': counts,
    'Percentage (%)': percentages
})

print(f'--- Frequency Distribution for: {col_target} ---')
display(freq_table)

--- Frequency Distribution for: Diseases during pregnancy ---

                           Frequency  Percentage (%)
Diseases during pregnancy
NaN                              371          46.375
Non-Chronic Disease              295          36.875
Chronic Disease                  134          16.750

In [ ]:
# Clean column names
df.columns = df.columns.str.strip()

# Clean text values in all object/categorical columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

# Replace inconsistent labels
replacement_map = {
    'মাঝে মধ্যে (Several days)': 'Several days',
    'Several Days': 'Several days',
    'several days': 'Several days'
}

df = df.replace(replacement_map)

# Verify
for col in df.select_dtypes(include='object').columns:
    if df[col].astype(str).str.contains('Several', case=False, na=False).any():
        print("\nColumn:", col)
        print(df[col].value_counts(dropna=False))

Column: Feeling down, depressed, or hopeless
Feeling down, depressed, or hopeless
Several days            361
Nearly every day        215
Not at all              159
Around half the days     65
Name: count, dtype: int64

Column: Trouble falling or staying asleep, or sleeping too much
Trouble falling or staying asleep, or sleeping too much
Nearly every day        325
Several days            296
Not at all              110
Around half the days     69
Name: count, dtype: int64

Column: Feeling tired or having little energy
Feeling tired or having little energy
Several days            416
Nearly every day        234
Around half the days     77
Not at all               73
Name: count, dtype: int64

Column: Poor appetite or overeating
Poor appetite or overeating
Several days            374
Not at all              218
Nearly every day        115
Around half the days     93
Name: count, dtype: int64

Column: Feeling bad about yourself or that you are a failure or have let yourself or your family down
Feeling bad about yourself or that you are a failure or have let yourself or your family down
Several days            324
Not at all              299
Nearly every day        128
Around half the days     49
Name: count, dtype: int64

Column: Trouble concentrating on things
Trouble concentrating on things
Several days            389
Nearly every day        179
Not at all              173
Around half the days     59
Name: count, dtype: int64

Column: Moving or speaking or restlessness
Moving or speaking or restlessness
Several days            292
Not at all              288
Nearly every day        161
Around half the days     59
Name: count, dtype: int64

Column: Thoughts that you would be better off dead, or of hurting yourself
Thoughts that you would be better off dead, or of hurting yourself
Not at all              598
Several days            151
Nearly every day         29
Around half the days     22
Name: count, dtype: int64

Column: You have been able to laugh and see the funny side of things
You have been able to laugh and see the funny side of things
Several days            410
Nearly every day        169
Not at all              136
Around half the days     85
Name: count, dtype: int64

Column: You have looked forward with enjoyment to things
You have looked forward with enjoyment to things
Several days            410
Nearly every day        169
Not at all              136
Around half the days     85
Name: count, dtype: int64

Column: You have blamed myself unnecessarily when things went wrong
You have blamed myself unnecessarily when things went wrong
Several days            324
Not at all              299
Nearly every day        128
Around half the days     49
Name: count, dtype: int64

Column: You have been anxious or worried for no good reason
You have been anxious or worried for no good reason
Several days            361
Nearly every day        215
Not at all              159
Around half the days     65
Name: count, dtype: int64

Column: You have felt scared or panicky for no good reason
You have felt scared or panicky for no good reason
Not at all              369
Several days            287
Nearly every day        107
Around half the days     37
Name: count, dtype: int64

Column: Things have been getting to you
Things have been getting to you
Several days            389
Nearly every day        179
Not at all              173
Around half the days     59
Name: count, dtype: int64

Column: You have been so unhappy that you have had difficulty sleeping
You have been so unhappy that you have had difficulty sleeping
Nearly every day        325
Several days            296
Not at all              110
Around half the days     69
Name: count, dtype: int64

Column: You have felt sad or miserable
You have felt sad or miserable
Several days            361
Nearly every day        215
Not at all              159
Around half the days     65
Name: count, dtype: int64

Column: You have been so unhappy that you have been crying
You have been so unhappy that you have been crying
Several days            417
Not at all              217
Nearly every day        116
Around half the days     50
Name: count, dtype: int64

Column: The thought of harming yourself has occurred
The thought of harming yourself has occurred
Not at all              598
Several days            151
Nearly every day         29
Around half the days     22
Name: count, dtype: int64

In [ ]:
cols_to_fix = ['Occupation before latest pregnancy', 'Occupation After Your Latest Childbirth']

# Correct spelling
for col in cols_to_fix:
    df[col] = df[col].replace('House wife', 'Housewife')

# Check frequencies
for col in cols_to_fix:
    print(f'--- Frequency Distribution for: {col} ---')
    counts = df[col].value_counts(dropna=False)
    percentages = df[col].value_counts(dropna=False, normalize=True) * 100

    summary = pd.DataFrame({
        'Frequency': counts,
        'Percentage (%)': percentages
    })
    display(summary)
    print('\n')

--- Frequency Distribution for: Occupation before latest pregnancy ---

                                    Frequency  Percentage (%)
Occupation before latest pregnancy
Housewife                                 391          48.875
Student                                   139          17.375
Teacher                                    78           9.750
Service                                    74           9.250
Other                                      65           8.125
Doctor                                     40           5.000
Business                                   13           1.625

--- Frequency Distribution for: Occupation After Your Latest Childbirth ---

                                         Frequency  Percentage (%)
Occupation After Your Latest Childbirth
Housewife                                      535          66.875
Student                                         70           8.750
Service                                         59           7.375
Teacher                                         47           5.875
Doctor                                          38           4.750
Other                                           37           4.625
Business                                        14           1.750

In [ ]:
# Check duplicates
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

print("Shape after removing duplicates:", df.shape)

Duplicate rows: 0
Shape after removing duplicates: (800, 69)

Unique values

In [ ]:
for col in df.columns:
    print(f"Unique values for {col}:")
    print(df[col].unique())

Unique values for Age:
[24 31 32 27 29 30 23 36 40 22 25 28 34 33 26 19 37 18 20 38 21 35 41 42
 45]
Unique values for Residence:
['City' 'Village']
Unique values for Education Level:
['University' 'College' 'Primary School' 'High School' nan]
Unique values for Marital status:
['Married' 'Divorced']
Unique values for Occupation before latest pregnancy:
['Student' 'Doctor' 'Service' 'Housewife' 'Teacher' 'Other' 'Business']
Unique values for Monthly income before latest pregnancy:
[nan '10000 to 20000' 'More than 30000' 'Less than 5000' '5000 to 10000'
 '20000 to 30000']
Unique values for Occupation After Your Latest Childbirth:
['Student' 'Doctor' 'Service' 'Housewife' 'Teacher' 'Business' 'Other']
Unique values for Current monthly income:
[nan '10000 to 20000' 'More than 30000' 'Less than 5000' '5000 to 10000'
 '20000 to 30000']
Unique values for Husband's education level:
['University' nan 'College' 'Primary School' 'High School']
Unique values for Husband's monthly income:
['More than 30000' nan '10000 to 20000' '5000 to 10000' '20000 to 30000'
 'Less than 5000']
Unique values for Addiction:
[nan 'Smoking' 'Drinking' 'Drugs']
Unique values for Total children:
['One' 'Two' 'More than Two']
Unique values for Disease before pregnancy:
[nan 'Non-Chronic Disease' 'Chronic Disease']
Unique values for History of pregnancy loss:
[nan 'Miscarriage' 'Still-born Delivery']
Unique values for Family type:
['Nuclear' 'Joint']
Unique values for Number of household members:
['6 to 8' '2 to 5' '9 or more']
Unique values for Relationship with the in-laws:
['Neutral' 'Good' 'Bad' 'Friendly' 'Poor']
Unique values for Relationship with husband:
['Good' 'Neutral' 'Bad' 'Friendly' 'Poor']
Unique values for Relationship with the newborn:
['Good' 'Neutral' 'Bad' 'Very good']
Unique values for Relationship between father and newborn:
['Good' 'Neutral' 'Bad' 'Very good']
Unique values for Feeling about motherhood:
['Neutral' 'Happy' 'Sad']
Unique values for Received Support:
['High' 'Medium' 'Low']
Unique values for Need for Support:
['Medium' 'Low' nan 'High']
Unique values for Major changes or losses during pregnancy:
['Yes' 'No']
Unique values for Abuse:
['Yes' 'No' nan]
Unique values for Trust and share feelings:
['Yes' 'No' nan]
Unique values for Number of the latest pregnancy:
[1 2 3 4 5 7 6]
Unique values for Pregnancy length:
['10 months' '9 months' '8 months' 'Less than 5 months' '7 months'
 '6 months']
Unique values for Pregnancy plan:
['No' 'Yes']
Unique values for Regular checkups:
['Yes' 'No']
Unique values for Fear of pregnancy:
['Yes' 'No']
Unique values for Diseases during pregnancy:
[nan 'Chronic Disease' 'Non-Chronic Disease']
Unique values for Age of newborn:
['6 months to 1 year' 'Older than 1.5 year' '0 to 6 months'
 '1 year to 1.5 year']
Unique values for Age of immediate older children:
[nan '13yr or more' '1yr to 3yr' '7yr to 12yr' '4yr to 6yr']
Unique values for Mode of delivery:
['Normal Delivery' 'Caesarean Section']
Unique values for Gender of newborn:
['Boy' 'Girl']
Unique values for Birth complications:
['No' 'Yes']
Unique values for Breastfeed:
['Yes' 'No']
Unique values for Newborn illness:
['No' 'Yes']
Unique values for Worry about newborn:
['Yes' 'No']
Unique values for Relax/sleep when newborn is tended:
['Yes' 'No']
Unique values for Relax/sleep when the newborn is asleep:
['Yes' 'No']
Unique values for Angry after latest child birth:
['No' 'Yes']
Unique values for Feeling for regular activities:
['Worried' 'Tired' nan 'Afraid']
Unique values for Depression before pregnancy (PHQ2):
['Negative' 'Positive']
Unique values for Depression during pregnancy (PHQ2):
['Negative' 'Positive']
Unique values for Little interest or pleasure in doing things:
['Nearly every day' 'Around half the days' 'Not at all']
Unique values for Feeling down, depressed, or hopeless:
['Nearly every day' 'Not at all' 'Around half the days' 'Several days']
Unique values for Trouble falling or staying asleep, or sleeping too much:
['Not at all' 'Several days' 'Nearly every day' 'Around half the days']
Unique values for Feeling tired or having little energy:
['Nearly every day' 'Several days' 'Not at all' 'Around half the days']
Unique values for Poor appetite or overeating:
['Nearly every day' 'Several days' 'Around half the days' 'Not at all']
Unique values for Feeling bad about yourself or that you are a failure or have let yourself or your family down:
['Not at all' 'Around half the days' 'Several days' 'Nearly every day']
Unique values for Trouble concentrating on things:
['Several days' 'Nearly every day' 'Not at all' 'Around half the days']
Unique values for Moving or speaking or restlessness:
['Several days' 'Nearly every day' 'Not at all' 'Around half the days']
Unique values for Thoughts that you would be better off dead, or of hurting yourself:
['Not at all' 'Nearly every day' 'Around half the days' 'Several days']
Unique values for PHQ9 Score:
[14 16  5 11 13 27  6  7 22  9 10 19  4  8  2 15 12  3 20 24 17 21  1 23
  0 18 25 26]
Unique values for PHQ9 Result:
['Moderate' 'Moderately Severe' 'Mild' 'Severe' 'Minimal' 'Normal']
Unique values for You have been able to laugh and see the funny side of things:
['Not at all' 'Several days' 'Nearly every day' 'Around half the days']
Unique values for You have looked forward with enjoyment to things:
['Not at all' 'Several days' 'Nearly every day' 'Around half the days']
Unique values for You have blamed myself unnecessarily when things went wrong:
['Not at all' 'Around half the days' 'Several days' 'Nearly every day']
Unique values for You have been anxious or worried for no good reason:
['Nearly every day' 'Not at all' 'Around half the days' 'Several days']
Unique values for You have felt scared or panicky for no good reason:
['Not at all' 'Around half the days' 'Several days' 'Nearly every day']
Unique values for Things have been getting to you:
['Several days' 'Nearly every day' 'Not at all' 'Around half the days']
Unique values for You have been so unhappy that you have had difficulty sleeping:
['Not at all' 'Several days' 'Nearly every day' 'Around half the days']
Unique values for You have felt sad or miserable:
['Nearly every day' 'Not at all' 'Around half the days' 'Several days']
Unique values for You have been so unhappy that you have been crying:
['Not at all' 'Around half the days' 'Several days' 'Nearly every day']
Unique values for The thought of harming yourself has occurred:
['Not at all' 'Nearly every day' 'Around half the days' 'Several days']
Unique values for EPDS Score:
[13 20 16  5  7 23 30  3 15 26 12 14  6 19 10 17  1 22  9  8 21 27  4  2
 24 18 11  0 25 28 29]
Unique values for EPDS Result:
['High' 'Low' 'Medium']

In [ ]:
save_path = '/content/drive/MyDrive/thesis_ppd/PPD_data_updated_v33.csv'
df.to_csv(save_path, index=False)
print(f'Dataset successfully saved to: {save_path}')

Dataset successfully saved to: /content/drive/MyDrive/thesis_ppd/PPD_data_updated_v33.csv

freq

In [ ]:
# Identify categorical columns (object type)
categorical_cols = df.select_dtypes(include=['object']).columns

# Loop through each categorical column and display frequency/percentage
for col in categorical_cols:
    print(f'--- Frequency and Percentage for: {col} ---')

    counts = df[col].value_counts(dropna=False)
    percentages = df[col].value_counts(dropna=False, normalize=True) * 100

    # Combine into a summary table
    cat_stats = pd.DataFrame({
        'Frequency': counts,
        'Percentage (%)': percentages
    })

    display(cat_stats)
    print('\n')

--- Frequency and Percentage for: Residence ---

           Frequency  Percentage (%)
Residence
City             637          79.625
Village          163          20.375

--- Frequency and Percentage for: Education Level ---

                 Frequency  Percentage (%)
Education Level
University             588          73.500
College                 99          12.375
High School             71           8.875
Primary School          36           4.500
NaN                      6           0.750

--- Frequency and Percentage for: Marital status ---

                Frequency  Percentage (%)
Marital status
Married               795          99.375
Divorced                5           0.625

--- Frequency and Percentage for: Occupation before latest pregnancy ---

                                    Frequency  Percentage (%)
Occupation before latest pregnancy
Housewife                                 391          48.875
Student                                   139          17.375
Teacher                                    78           9.750
Service                                    74           9.250
Other                                      65           8.125
Doctor                                     40           5.000
Business                                   13           1.625

--- Frequency and Percentage for: Monthly income before latest pregnancy ---

                                        Frequency  Percentage (%)
Monthly income before latest pregnancy
NaN                                           437          54.625
10000 to 20000                                 92          11.500
5000 to 10000                                  86          10.750
20000 to 30000                                 77           9.625
More than 30000                                71           8.875
Less than 5000                                 37           4.625

--- Frequency and Percentage for: Occupation After Your Latest Childbirth ---

                                         Frequency  Percentage (%)
Occupation After Your Latest Childbirth
Housewife                                      535          66.875
Student                                         70           8.750
Service                                         59           7.375
Teacher                                         47           5.875
Doctor                                          38           4.750
Other                                           37           4.625
Business                                        14           1.750

--- Frequency and Percentage for: Current monthly income ---

                        Frequency  Percentage (%)
Current monthly income
NaN                           525          65.625
10000 to 20000                 66           8.250
More than 30000                64           8.000
20000 to 30000                 63           7.875
5000 to 10000                  42           5.250
Less than 5000                 40           5.000

--- Frequency and Percentage for: Husband's education level ---

                           Frequency  Percentage (%)
Husband's education level
University                       595          74.375
High School                       83          10.375
College                           75           9.375
Primary School                    38           4.750
NaN                                9           1.125

--- Frequency and Percentage for: Husband's monthly income ---

                          Frequency  Percentage (%)
Husband's monthly income
More than 30000                 343          42.875
20000 to 30000                  207          25.875
10000 to 20000                  146          18.250
5000 to 10000                    65           8.125
NaN                              28           3.500
Less than 5000                   11           1.375

--- Frequency and Percentage for: Addiction ---

           Frequency  Percentage (%)
Addiction
NaN              789          98.625
Smoking            8           1.000
Drinking           2           0.250
Drugs              1           0.125

--- Frequency and Percentage for: Total children ---

                Frequency  Percentage (%)
Total children
One                   518          64.750
Two                   223          27.875
More than Two          59           7.375

--- Frequency and Percentage for: Disease before pregnancy ---

                          Frequency  Percentage (%)
Disease before pregnancy
NaN                             589          73.625
Chronic Disease                 124          15.500
Non-Chronic Disease              87          10.875

--- Frequency and Percentage for: History of pregnancy loss ---

                           Frequency  Percentage (%)
History of pregnancy loss
NaN                              613          76.625
Miscarriage                      158          19.750
Still-born Delivery               29           3.625

--- Frequency and Percentage for: Family type ---

             Frequency  Percentage (%)
Family type
Nuclear            421          52.625
Joint              379          47.375

--- Frequency and Percentage for: Number of household members ---

                             Frequency  Percentage (%)
Number of household members
2 to 5                             524          65.500
6 to 8                             223          27.875
9 or more                           53           6.625

--- Frequency and Percentage for: Relationship with the in-laws ---

                               Frequency  Percentage (%)
Relationship with the in-laws
Neutral                              315          39.375
Good                                 310          38.750
Bad                                  134          16.750
Friendly                              33           4.125
Poor                                   8           1.000

--- Frequency and Percentage for: Relationship with husband ---

                           Frequency  Percentage (%)
Relationship with husband
Good                             578          72.250
Neutral                          113          14.125
Friendly                          52           6.500
Bad                               51           6.375
Poor                               6           0.750

--- Frequency and Percentage for: Relationship with the newborn ---

                               Frequency  Percentage (%)
Relationship with the newborn
Good                                 690          86.250
Very good                             65           8.125
Neutral                               38           4.750
Bad                                    7           0.875

--- Frequency and Percentage for: Relationship between father and newborn ---

                                         Frequency  Percentage (%)
Relationship between father and newborn
Good                                           654          81.750
Neutral                                         69           8.625
Very good                                       62           7.750
Bad                                             15           1.875

--- Frequency and Percentage for: Feeling about motherhood ---

                          Frequency  Percentage (%)
Feeling about motherhood
Happy                           671          83.875
Neutral                          94          11.750
Sad                              35           4.375

--- Frequency and Percentage for: Received Support ---

                  Frequency  Percentage (%)
Received Support
Medium                  339          42.375
High                    307          38.375
Low                     154          19.250

--- Frequency and Percentage for: Need for Support ---

                  Frequency  Percentage (%)
Need for Support
Low                     523          65.375
NaN                     167          20.875
Medium                   85          10.625
High                     25           3.125

--- Frequency and Percentage for: Major changes or losses during pregnancy ---

                                          Frequency  Percentage (%)
Major changes or losses during pregnancy
No                                              526           65.75
Yes                                             274           34.25

--- Frequency and Percentage for: Abuse ---

       Frequency  Percentage (%)
Abuse
Yes          403          50.375
No           359          44.875
NaN           38           4.750

--- Frequency and Percentage for: Trust and share feelings ---

                          Frequency  Percentage (%)
Trust and share feelings
Yes                             544          68.000
No                              255          31.875
NaN                               1           0.125

--- Frequency and Percentage for: Pregnancy length ---

                    Frequency  Percentage (%)
Pregnancy length
9 months                  438          54.750
10 months                 246          30.750
8 months                   71           8.875
Less than 5 months         22           2.750
7 months                   16           2.000
6 months                    7           0.875

--- Frequency and Percentage for: Pregnancy plan ---

                Frequency  Percentage (%)
Pregnancy plan
Yes                   568            71.0
No                    232            29.0

--- Frequency and Percentage for: Regular checkups ---

                  Frequency  Percentage (%)
Regular checkups
Yes                     752            94.0
No                       48             6.0

--- Frequency and Percentage for: Fear of pregnancy ---

                   Frequency  Percentage (%)
Fear of pregnancy
Yes                      486           60.75
No                       314           39.25

--- Frequency and Percentage for: Diseases during pregnancy ---

                           Frequency  Percentage (%)
Diseases during pregnancy
NaN                              371          46.375
Non-Chronic Disease              295          36.875
Chronic Disease                  134          16.750

--- Frequency and Percentage for: Age of newborn ---

                     Frequency  Percentage (%)
Age of newborn
0 to 6 months              344          43.000
1 year to 1.5 year         155          19.375
6 months to 1 year         153          19.125
Older than 1.5 year        148          18.500

--- Frequency and Percentage for: Age of immediate older children ---

                                 Frequency  Percentage (%)
Age of immediate older children
NaN                                    517          64.625
4yr to 6yr                             112          14.000
1yr to 3yr                             109          13.625
7yr to 12yr                             55           6.875
13yr or more                             7           0.875

--- Frequency and Percentage for: Mode of delivery ---

                   Frequency  Percentage (%)
Mode of delivery
Caesarean Section        560            70.0
Normal Delivery          240            30.0

--- Frequency and Percentage for: Gender of newborn ---

                   Frequency  Percentage (%)
Gender of newborn
Boy                      409          51.125
Girl                     391          48.875

--- Frequency and Percentage for: Birth complications ---

                     Frequency  Percentage (%)
Birth complications
No                         487          60.875
Yes                        313          39.125

--- Frequency and Percentage for: Breastfeed ---

            Frequency  Percentage (%)
Breastfeed
Yes               719          89.875
No                 81          10.125

--- Frequency and Percentage for: Newborn illness ---

                 Frequency  Percentage (%)
Newborn illness
No                     662           82.75
Yes                    138           17.25

--- Frequency and Percentage for: Worry about newborn ---

                     Frequency  Percentage (%)
Worry about newborn
Yes                        470           58.75
No                         330           41.25

--- Frequency and Percentage for: Relax/sleep when newborn is tended ---

                                    Frequency  Percentage (%)
Relax/sleep when newborn is tended
Yes                                       455          56.875
No                                        345          43.125

--- Frequency and Percentage for: Relax/sleep when the newborn is asleep ---

                                        Frequency  Percentage (%)
Relax/sleep when the newborn is asleep
Yes                                           594           74.25
No                                            206           25.75

--- Frequency and Percentage for: Angry after latest child birth ---

                                Frequency  Percentage (%)
Angry after latest child birth
Yes                                   539          67.375
No                                    261          32.625

--- Frequency and Percentage for: Feeling for regular activities ---

                                Frequency  Percentage (%)
Feeling for regular activities
Tired                                 335          41.875
NaN                                   223          27.875
Worried                               175          21.875
Afraid                                 67           8.375

--- Frequency and Percentage for: Depression before pregnancy (PHQ2) ---

                                    Frequency  Percentage (%)
Depression before pregnancy (PHQ2)
Negative                                  719          89.875
Positive                                   81          10.125

--- Frequency and Percentage for: Depression during pregnancy (PHQ2) ---

                                    Frequency  Percentage (%)
Depression during pregnancy (PHQ2)
Negative                                  616            77.0
Positive                                  184            23.0

--- Frequency and Percentage for: Little interest or pleasure in doing things ---

                                             Frequency  Percentage (%)
Little interest or pleasure in doing things
Around half the days                               410           51.25
Not at all                                         254           31.75
Nearly every day                                   136           17.00

--- Frequency and Percentage for: Feeling down, depressed, or hopeless ---

                                      Frequency  Percentage (%)
Feeling down, depressed, or hopeless
Several days                                361          45.125
Nearly every day                            215          26.875
Not at all                                  159          19.875
Around half the days                         65           8.125

--- Frequency and Percentage for: Trouble falling or staying asleep, or sleeping too much ---

                                                    Frequency  Percentage (%)
Trouble falling or staying asleep, or sleeping ...
Nearly every day                                          325          40.625
Several days                                              296          37.000
Not at all                                                110          13.750
Around half the days                                       69           8.625

--- Frequency and Percentage for: Feeling tired or having little energy ---

                                       Frequency  Percentage (%)
Feeling tired or having little energy
Several days                                 416          52.000
Nearly every day                             234          29.250
Around half the days                          77           9.625
Not at all                                    73           9.125

--- Frequency and Percentage for: Poor appetite or overeating ---

                             Frequency  Percentage (%)
Poor appetite or overeating
Several days                       374          46.750
Not at all                         218          27.250
Nearly every day                   115          14.375
Around half the days                93          11.625

--- Frequency and Percentage for: Feeling bad about yourself or that you are a failure or have let yourself or your family down ---

                                                    Frequency  Percentage (%)
Feeling bad about yourself or that you are a fa...
Several days                                              324          40.500
Not at all                                                299          37.375
Nearly every day                                          128          16.000
Around half the days                                       49           6.125

--- Frequency and Percentage for: Trouble concentrating on things ---

                                 Frequency  Percentage (%)
Trouble concentrating on things
Several days                           389          48.625
Nearly every day                       179          22.375
Not at all                             173          21.625
Around half the days                    59           7.375

--- Frequency and Percentage for: Moving or speaking or restlessness ---

                                    Frequency  Percentage (%)
Moving or speaking or restlessness
Several days                              292          36.500
Not at all                                288          36.000
Nearly every day                          161          20.125
Around half the days                       59           7.375

--- Frequency and Percentage for: Thoughts that you would be better off dead, or of hurting yourself ---

                                                    Frequency  Percentage (%)
Thoughts that you would be better off dead, or ...
Not at all                                                598          74.750
Several days                                              151          18.875
Nearly every day                                           29           3.625
Around half the days                                       22           2.750

--- Frequency and Percentage for: PHQ9 Result ---

                   Frequency  Percentage (%)
PHQ9 Result
Moderate                 237          29.625
Mild                     231          28.875
Moderately Severe        132          16.500
Minimal                  103          12.875
Severe                    89          11.125
Normal                     8           1.000

--- Frequency and Percentage for: You have been able to laugh and see the funny side of things ---

                                                    Frequency  Percentage (%)
You have been able to laugh and see the funny s...
Several days                                              410          51.250
Nearly every day                                          169          21.125
Not at all                                                136          17.000
Around half the days                                       85          10.625

--- Frequency and Percentage for: You have looked forward with enjoyment to things ---

                                                  Frequency  Percentage (%)
You have looked forward with enjoyment to things
Several days                                            410          51.250
Nearly every day                                        169          21.125
Not at all                                              136          17.000
Around half the days                                     85          10.625

--- Frequency and Percentage for: You have blamed myself unnecessarily when things went wrong ---

                                                    Frequency  Percentage (%)
You have blamed myself unnecessarily when thing...
Several days                                              324          40.500
Not at all                                                299          37.375
Nearly every day                                          128          16.000
Around half the days                                       49           6.125

--- Frequency and Percentage for: You have been anxious or worried for no good reason ---

                                                    Frequency  Percentage (%)
You have been anxious or worried for no good re...
Several days                                              361          45.125
Nearly every day                                          215          26.875
Not at all                                                159          19.875
Around half the days                                       65           8.125

--- Frequency and Percentage for: You have felt scared or panicky for no good reason ---

                                                    Frequency  Percentage (%)
You have felt scared or panicky for no good reason
Not at all                                                369          46.125
Several days                                              287          35.875
Nearly every day                                          107          13.375
Around half the days                                       37           4.625

--- Frequency and Percentage for: Things have been getting to you ---

                                 Frequency  Percentage (%)
Things have been getting to you
Several days                           389          48.625
Nearly every day                       179          22.375
Not at all                             173          21.625
Around half the days                    59           7.375

--- Frequency and Percentage for: You have been so unhappy that you have had difficulty sleeping ---

                                                    Frequency  Percentage (%)
You have been so unhappy that you have had diff...
Nearly every day                                          325          40.625
Several days                                              296          37.000
Not at all                                                110          13.750
Around half the days                                       69           8.625

--- Frequency and Percentage for: You have felt sad or miserable ---

                                Frequency  Percentage (%)
You have felt sad or miserable
Several days                          361          45.125
Nearly every day                      215          26.875
Not at all                            159          19.875
Around half the days                   65           8.125

--- Frequency and Percentage for: You have been so unhappy that you have been crying ---

                                                    Frequency  Percentage (%)
You have been so unhappy that you have been crying
Several days                                              417          52.125
Not at all                                                217          27.125
Nearly every day                                          116          14.500
Around half the days                                       50           6.250

--- Frequency and Percentage for: The thought of harming yourself has occurred ---

                                              Frequency  Percentage (%)
The thought of harming yourself has occurred
Not at all                                          598          74.750
Several days                                        151          18.875
Nearly every day                                     29           3.625
Around half the days                                 22           2.750

--- Frequency and Percentage for: EPDS Result ---

             Frequency  Percentage (%)
EPDS Result
High               350           43.75
Low                260           32.50
Medium             190           23.75

In [ ]:
missing_table = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum() / len(df)) * 100
})

missing_table = missing_table[missing_table['Missing Count'] > 0]
missing_table = missing_table.sort_values(by='Missing Percentage', ascending=False)

missing_table

Nymerical Feature handle

In [ ]:

# Check target variable
print(df['EPDS Result'].value_counts())
print(df['EPDS Result'].value_counts(normalize=True) * 100)

# Check numerical columns
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
print("Numerical columns:", numerical_cols)

# Check remaining object columns
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print("Categorical columns:", len(categorical_cols))

EPDS Result
High      350
Low       260
Medium    190
Name: count, dtype: int64
EPDS Result
High      43.75
Low       32.50
Medium    23.75
Name: proportion, dtype: float64
Numerical columns: ['Age', 'Number of the latest pregnancy', 'PHQ9 Score', 'EPDS Score']
Categorical columns: 65

In [ ]:
# 1. Numerical Descriptive Statistics
print("--- Numerical Statistics Summary ---")
display(df.describe().T)

--- Numerical Statistics Summary ---

,count,mean,std,min,25%,50%,75%,max
Age,800.0,27.72500,4.465625,18.0,25.0,27.0,31.0,45.0
Number of the latest pregnancy,800.0,1.63125,0.895140,1.0,1.0,1.0,2.0,7.0
PHQ9 Score,800.0,11.30750,5.769710,0.0,7.0,11.0,15.0,27.0
EPDS Score,800.0,12.46250,7.097998,0.0,7.0,11.0,17.0,30.0